Repository ArduPilot/MAVProxy, pull requests merged in 2024-01, with the labels that each got.

#1302 horizon: use keyword arg for radius
  MAVProxy/modules/lib/wxhorizon_ui.py
Labels: MacOS

#1305 macOS: remove deprecated and unused imports
  MAVProxy/modules/lib/MacOS/backend_wxagg.py
Labels: bug, MacOS

#1312 mission_item_protocol: add support for upload/download of fence/rally…
  MAVProxy/modules/lib/mission_item_protocol.py
  MAVProxy/modules/mavproxy_fence.py
  MAVProxy/modules/mavproxy_rally.py
  MAVProxy/modules/mavproxy_wp.py
Labels: DevCallEU

#1311 map: add altitude information to click data
  MAVProxy/modules/mavproxy_map/mp_slipmap_ui.py
Labels: DevCallEU
